### ISSUE TITLE
it doesn show the pic,  fix included

### ISSUE THREAD

**Issue by fritol** [Doriandarko/Moondream1-streamlit#1]
# File uploader for the image
uploaded_image = st.file_uploader("Upload an image", type=["png", "jpg", "jpeg"])
if uploaded_image is not None:
    st.session_state['uploaded_image'] = uploaded_image
    # Display the uploaded image
    image = Image.open(uploaded_image)
    st.image(image, caption='Uploaded Image.', use_column_width=True)

**Comment by Doriandarko** [comment]
Added that capability! Thank you!
